The Big Scaffolding Adoption, part 1: technicalities
gramineproject/gramine-scaffolding pull request #2
Opened 2024-01-24 16:06 UTC by woju

2024-01-25 12:44 UTC, dimakuv requested changes
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/2)* status: all files reviewed, 14 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

___
*[`.gitignore` line 14 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/2#-Np-_dJr5iharJkQAudH:-Np-_dJr5iharJkQAudI:brj9se5) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/7adb516b9ee3a09abf07617ac593fadd577d7e14/.gitignore#L14)):*
> ```ignore
> /debian/files
> /debian/gramine-scaffolding*/
> /debian/tmp/
> ```

This change (with `/debian/`) seems to belong into another PR, but I'm not blocking.
___
*[`CODE_OF_CONDUCT.md` line 63 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/2#-Np-_zPj9u9avpVzqYg8:-Np-_zPj9u9avpVzqYg9:bmomggq) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/7adb516b9ee3a09abf07617ac593fadd577d7e14/CODE_OF_CONDUCT.md#L63)):*
> ```Markdown
> Instances of abusive, harassing, or otherwise unacceptable behavior may be
> reported to the community leaders responsible for enforcement at
> CommunityCodeOfConduct AT intel DOT com.
> ```

What is this email? Shouldn't you use the text from Gramine core: https://github.com/gramineproject/gramine/blob/36676a75e9897c9b7b183157a9d9fcdf2f668a13/CODE_OF_CONDUCT.rst?plain=1#L68-L73
___
*[`CODE_OF_CONDUCT.md` line 126 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/2#-Np-aP0l6-sHU9PBHa0T:-Np-aP0l6-sHU9PBHa0U:bdwxttm) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/7adb516b9ee3a09abf07617ac593fadd577d7e14/CODE_OF_CONDUCT.md#L126)):*
> ```Markdown
> For answers to common questions about this code of conduct, see the FAQ at
> [https://www.contributor-covenant.org/faq][FAQ]. Translations are available at
> [https://www.contributor-covenant.org/translations][translations].
> ```

This renders incorrectly because it doesn't have the corresponding link below.
___
*[`CONTRIBUTING.md` line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/2#-Np-b4AT9FmF0EWPD16O:-Np-b4AT9FmF0EWPD16P:bcorsdi) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/7adb516b9ee3a09abf07617ac593fadd577d7e14/CONTRIBUTING.md#L5)):*
> ```Markdown
> ### License
> 
> Scaffolding for Gramine is licensed under the terms in [COPYING](COPYING). By contributing to the project, you agree to the license and copyright terms therein and release your contribution under these terms.
> ```

If you'll change the name to `LICENSE.txt`, please also update here.
___
*[`CONTRIBUTING.md` line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/2#-Np-bALYB8G96L4SviSd:-Np-bALYB8G96L4SviSe:b29uwtg) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/7adb516b9ee3a09abf07617ac593fadd577d7e14/CONTRIBUTING.md#L5)):*
> ```Markdown
> ### License
> 
> Scaffolding for Gramine is licensed under the terms in [COPYING](COPYING). By contributing to the project, you agree to the license and copyright terms therein and release your contribution under these terms.
> ```

Shouldn't this whole file be 80 chars per line?
___
*[`CONTRIBUTING.md` line 12 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/2#-Np-bMqbAt8zKDru4xUT:-Np-bMqbAt8zKDru4xUU:b-jetzwv) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/7adb516b9ee3a09abf07617ac593fadd577d7e14/CONTRIBUTING.md#L12)):*
> ```Markdown
> the below (from [developercertificate.org](http://developercertificate.org/)):
> 
> ```
> ```

Why do we have a copy and paste of the DCO? Can't you just insert a link to the DCO file, and remove the text?
___
*[`COPYING` line 1 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/2#-Np-aefd9inh1Pp-wddG:-Np-aefd9inh1Pp-wddH:b6nrf6i) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/7adb516b9ee3a09abf07617ac593fadd577d7e14/COPYING#L1)):*
> ```
>                    GNU LESSER GENERAL PUBLIC LICENSE
> ```

Shouldn't this file be `LICENSE.txt`: https://github.com/gramineproject/gramine/blob/36676a75e9897c9b7b183157a9d9fcdf2f668a13/LICENSE.txt
___
*[`README.rst` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/2#-Np-cPwi8njalZie5Ydz:-Np-cPwi8njalZie5Ye-:b-x02ctj) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/7adb516b9ee3a09abf07617ac593fadd577d7e14/README.rst#L4)):*
> ```reStructuredText
> Scaffolding for Gramine
> ***********************
> ```

It's weird that there is no introduction and explanation what Scaffolding is... Is this on purpose?
___
*[`README.rst` line 11 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/2#-Np-c1yb7tZR4Pg84hKL:-Np-c1yb7tZR4Pg84hKM:b-fmq0qk) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/7adb516b9ee3a09abf07617ac593fadd577d7e14/README.rst#L11)):*
> ```reStructuredText
> ---------------------------
> 
> First, you need to install Gramine 1.6 from upstream repositories. In this
> ```

Why do you hard-code `v1.6` here? Shouldn't you just use "latest release of Gramine" (and at least v1.6)?
___
*[`README.rst` line 13 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/2#-Np-cCTX8sPVmJLc3pFI:-Np-cCTY24paK3Qf_KNk:bokqhgu) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/7adb516b9ee3a09abf07617ac593fadd577d7e14/README.rst#L13)):*
> ```reStructuredText
> First, you need to install Gramine 1.6 from upstream repositories. In this
> example, codename is e.g., ``bookworm`` for Debian 12, but for Ubuntu this might
> be written as ``$(lsb_release -sc)`` substitution in the manual.
> ```

`in the manual` -- which manual? This README? Why not just say "in below commands", or just remove this phrase altogether?
___
*[`README.rst` line 52 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/2#-Np-cjQSCLVOADdvpmHM:-Np-cjQSCLVOADdvpmHN:b3452f0) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/7adb516b9ee3a09abf07617ac593fadd577d7e14/README.rst#L52)):*
> ```reStructuredText
> 
>     # sudo apt-get update && sudo apt-get install devscripts # if you didn't already
>     sudo apt-get build-dep . -t bullseye-backports
> ```

The only difference is this `bullseye-backports`. Why is this needed? Will it also be a problem on Ubuntu 22.04?
___
*[`README.rst` line 71 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/2#-Np-dR_p-WCE66yhuCjO:-Np-dR_q4L6uR0OdqmpU:b-ao4co3) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/7adb516b9ee3a09abf07617ac593fadd577d7e14/README.rst#L71)):*
> ```reStructuredText
> 
> First, install gramine as described in
> https://gramine.rtfd.io/en/stable/installation.html#install-gramine-packages .
> ```

Above you have full descriptions how to install Gramine, but here you have only a link to the Gramine installation guide. Can you unify?
___
*[`README.rst` line 100 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/2#-Np-ddFd4z17CEqlPqtr:-Np-ddFe86eL_6tM-zkh:b-qafbpx) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/7adb516b9ee3a09abf07617ac593fadd577d7e14/README.rst#L100)):*
> ```reStructuredText
>     scag-quickstart
> 
> .. vim: ts=4 sts=4 sw=4 et
> ```

Why this? Do you want to keep this vim setting?
___
*[`SECURITY.md` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/2#-Np-atgW4PW0RcTKpBRW:-Np-atgW4PW0RcTKpBRX:b-x49z5k) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/7adb516b9ee3a09abf07617ac593fadd577d7e14/SECURITY.md#L2)):*
> ```Markdown
> # Security Policy
> Intel is committed to rapidly addressing security vulnerabilities affecting our customers and providing clear guidance on the solution, impact,  [...]

2024-01-25 16:03 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/2)* status: 8 of 10 files reviewed, 14 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[`.gitignore` line 14 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/2#-Np-_dJr5iharJkQAudH:-Np0Igb44SGq0_QLmjIH:b-hacyn0) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/7adb516b9ee3a09abf07617ac593fadd577d7e14/.gitignore#L14)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This change (with `/debian/`) seems to belong into another PR, but I'm not blocking.
</blockquote></details>

Every single line belongs elsewhere, python stuff belongs to #3. If possible, I'd like to keep it here as whole, to avoid possible conflicts. Alternatively I can move it at the very end of the PR train, because it doesn't break anything if the file is not present and you feel that we might miss something.
___
*[`CODE_OF_CONDUCT.md` line 63 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/2#-Np-_zPj9u9avpVzqYg8:-Np0JUX38nJzlnuTv9uK:b-nsqzfh) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/7adb516b9ee3a09abf07617ac593fadd577d7e14/CODE_OF_CONDUCT.md#L63)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What is this email? Shouldn't you use the text from Gramine core: https://github.com/gramineproject/gramine/blob/36676a75e9897c9b7b183157a9d9fcdf2f668a13/CODE_OF_CONDUCT.rst?plain=1#L68-L73
</blockquote></details>

Can I just remove it? Only main repo has code of conduct, and it applies everywhere.
___
*[`CODE_OF_CONDUCT.md` line 126 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/2#-Np-aP0l6-sHU9PBHa0T:-Np0KulqA-wEH8WxKAZO:b-ngdc8p) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/7adb516b9ee3a09abf07617ac593fadd577d7e14/CODE_OF_CONDUCT.md#L126)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This renders incorrectly because it doesn't have the corresponding link below.
</blockquote></details>

I'll fix if we decide to keep it (see above discussion).
___
*[`CONTRIBUTING.md` line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/2#-Np-bALYB8G96L4SviSd:-Np0L-JA1SqDtgQCJXRa:b-jyubx0) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/7adb516b9ee3a09abf07617ac593fadd577d7e14/CONTRIBUTING.md#L5)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Shouldn't this whole file be 80 chars per line?
</blockquote></details>

I was copied verbatim from somewhere.

What should we do with this thing? We can either remove it (again, only main repo has this file), or maybe we can have just a link to main repo?
___
*[`CONTRIBUTING.md` line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/2#-Np-b4AT9FmF0EWPD16O:-Np0LYyZ0TAfiaLrtlmI:bocrjka) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/7adb516b9ee3a09abf07617ac593fadd577d7e14/CONTRIBUTING.md#L5)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

If you'll change the name to `LICENSE.txt`, please also update here.
</blockquote></details>

Wilco, when we finish other discussion.
___
*[`CONTRIBUTING.md` line 12 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/2#-Np-bMqbAt8zKDru4xUT:-Np0LSqcBmiNC0WfELSu:b5dmmx2) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/7adb516b9ee3a09abf07617ac593fadd577d7e14/CONTRIBUTING.md#L12)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do we have a copy and paste of the DCO? Can't you just insert a link to the DCO file, and remove the text?
</blockquote></details>

Again, it was copied verbatim from somewhere, to comply with a checklist.
___
*[`COPYING` line 1 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/2#-Np-aefd9inh1Pp-wddG:-Np0Js-91LMiiVyq9WmU:b-yp9uhx) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/7adb516b9ee3a09abf07617ac593fadd577d7e14/COPYING#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Shouldn't this file be `LICENSE.txt`: https://github.com/gramineproject/gramine/blob/36676a75e9897c9b7b183157a9d9fcdf2f668a13/LICENSE.txt
</blockquote></details>

Not necessarily, `COPYING` is fine and historically widely used. It's recognized in Github just fine (you can't see it in branch, but in very old repo of this project it's there just fine: https://github.com/woju/gramine-scaffolding).
___
*[`README.rst` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/2#-Np-cPwi8njalZie5Ydz:-Np-gE7bAyxi-tPVwa88:bbcqtg7) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/7adb516b9ee3a09abf07617ac593fadd577d7e14/README.rst#L4)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

It's weird that there is no introduction and explanation what Scaffolding is... Is this on purpose?
</blockquote></details>

"Scaffolding" is jargon name for a generator of boilerplate for new project, a.k.a. "project boostrap tool" or "skeleton". Here are some examples of dedicated tools for this: https://www.cookiecutter.io/article-post/cookiecutter-alternatives

It's not "on purpose", but we didn't feel the need to 
___
*[`README.rst` line 11 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/2#-Np-c1yb7tZR4Pg84hKL:-Np0IF7n2UhcK1_EMcwF:b-shrrnq) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/7adb516b9ee3a09abf07617ac593fadd577d7e14/README.rst#L11)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you hard-code `v1.6` here? Shouldn't you just use "latest release of Gramine" (and at least v1.6)?
</blockquote></details>

Done.

Why did I hardcode: previous version said that you needed to install *1.6~rcsomething* from *unstable* repositories.
___
*[`README.rst` line 13 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/2#-Np-cCTX8sPVmJLc3pFI:-Np0IU5QAhN966zvKAtl:bj2b1on) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/7adb516b9ee3a09abf07617ac593fadd577d7e14/README.rst#L13)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`in the manual` -- which manual? This README? Why not just say "in below commands", or just remove this phrase altogether?
</blockquote></details>

`$(lsb_release)` is used in main repo. I've rephrased.
___
*[`README.rst` line 52 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/2#-Np-cjQSCLVOADdvpmHM:-Np-hRE9C5cHmL3ieYCW:betiflo) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/7adb516b9ee3a09abf07617ac593fadd577d7e14/README.rst#L52)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The only difference is this `bullseye-backports`. Why is this needed? Will it also be a problem on Ubuntu 22.04?
</blockquote></details>

Because `gramine` itself needs packages from backports, and `gramine` is in `Build-Depends:` (see quickstart in main repo).

Ubuntu 22.04 LTS and earlier versions have problems with too old dependencies (IIRC setuptools or something else within python packaging toolchain; right now I can't recall exactly what) and also it doesn't ship Debian keyring which is needed to bootstrap (mmdebstrap) bookworm image. So 22.04 is not well supported, you can't build deb package on it (only install stuff from pip into venv, see below), and there are hacks in place like vendoring this keyring [...]

2024-01-26 15:20 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/2)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

___
*[`.gitignore` line 14 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/2#-Np-_dJr5iharJkQAudH:-Np5LEnr5SDc2TRuRPyy:b8z8ph6) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/7adb516b9ee3a09abf07617ac593fadd577d7e14/.gitignore#L14)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Every single line belongs elsewhere, python stuff belongs to #3. If possible, I'd like to keep it here as whole, to avoid possible conflicts. Alternatively I can move it at the very end of the PR train, because it doesn't break anything if the file is not present and you feel that we might miss something.
</blockquote></details>

Yes, agreed. Let's not bother.
___
*[`CODE_OF_CONDUCT.md` line 63 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/2#-Np-_zPj9u9avpVzqYg8:-Np5LLwN2cMoE15tYjzI:bgymtg6) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/7adb516b9ee3a09abf07617ac593fadd577d7e14/CODE_OF_CONDUCT.md#L63)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Can I just remove it? Only main repo has code of conduct, and it applies everywhere.
</blockquote></details>

Yes, let's remove it.
___
*[`CODE_OF_CONDUCT.md` line 126 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/2#-Np-aP0l6-sHU9PBHa0T:-Np5LN0512l9bjd-Lerj:bgymtg6) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/7adb516b9ee3a09abf07617ac593fadd577d7e14/CODE_OF_CONDUCT.md#L126)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

I'll fix if we decide to keep it (see above discussion).
</blockquote></details>

Yes, let's remove it.
___
*[`CONTRIBUTING.md` line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/2#-Np-bALYB8G96L4SviSd:-Np5LS7DCjnsHFE3cuD1:bgymtg6) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/7adb516b9ee3a09abf07617ac593fadd577d7e14/CONTRIBUTING.md#L5)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

I was copied verbatim from somewhere.

What should we do with this thing? We can either remove it (again, only main repo has this file), or maybe we can have just a link to main repo?
</blockquote></details>

Yes, let's remove it.
___
*[`CONTRIBUTING.md` line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/2#-Np-b4AT9FmF0EWPD16O:-Np5LSb062RdvWRWENhP:bgymtg6) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/7adb516b9ee3a09abf07617ac593fadd577d7e14/CONTRIBUTING.md#L5)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Wilco, when we finish other discussion.
</blockquote></details>

Yes, let's remove it.
___
*[`CONTRIBUTING.md` line 12 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/2#-Np-bMqbAt8zKDru4xUT:-Np5LTIV7pvw9O0URvoA:bgymtg6) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/7adb516b9ee3a09abf07617ac593fadd577d7e14/CONTRIBUTING.md#L12)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Again, it was copied verbatim from somewhere, to comply with a checklist.
</blockquote></details>

Yes, let's remove it.
___
*[`COPYING` line 1 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/2#-Np-aefd9inh1Pp-wddG:-Np5LWtn70jhZ4dzrxky:b32w1t) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/7adb516b9ee3a09abf07617ac593fadd577d7e14/COPYING#L1)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Not necessarily, `COPYING` is fine and historically widely used. It's recognized in Github just fine (you can't see it in branch, but in very old repo of this project it's there just fine: https://github.com/woju/gramine-scaffolding).
</blockquote></details>

Ok


<!-- Sent from Reviewable.io -->

2024-01-26 15:40 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/2)* status: 8 of 10 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[`CODE_OF_CONDUCT.md` line 63 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/2#-Np-_zPj9u9avpVzqYg8:-Np5PWy-0IvSbi-NIpy4:b-896fix) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/7adb516b9ee3a09abf07617ac593fadd577d7e14/CODE_OF_CONDUCT.md#L63)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, let's remove it.
</blockquote></details>

Done.
___
*[`CODE_OF_CONDUCT.md` line 126 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/2#-Np-aP0l6-sHU9PBHa0T:-Np5PYtd09RH9XqQAoCt:b-896fix) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/7adb516b9ee3a09abf07617ac593fadd577d7e14/CODE_OF_CONDUCT.md#L126)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, let's remove it.
</blockquote></details>

Done.
___
*[`CONTRIBUTING.md` line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/2#-Np-bALYB8G96L4SviSd:-Np5PbXu90iIw2etP5y4:b-896fix) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/7adb516b9ee3a09abf07617ac593fadd577d7e14/CONTRIBUTING.md#L5)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, let's remove it.
</blockquote></details>

Done.
___
*[`CONTRIBUTING.md` line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/2#-Np-b4AT9FmF0EWPD16O:-Np5Pd-FB_CUOS-yvpEf:b-896fix) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/7adb516b9ee3a09abf07617ac593fadd577d7e14/CONTRIBUTING.md#L5)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, let's remove it.
</blockquote></details>

Done.
___
*[`CONTRIBUTING.md` line 12 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/2#-Np-bMqbAt8zKDru4xUT:-Np5PcSf8LYMguRXXHaB:b-896fix) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/7adb516b9ee3a09abf07617ac593fadd577d7e14/CONTRIBUTING.md#L12)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, let's remove it.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-01-29 07:31 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/2)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @woju)

___
*[`-- commits` line 16 at r3](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/2#-NpJ76y13Mi7tZCfoohL):*
Do you want this second commit to be seen in the final merge, or should we squash it?


<!-- Sent from Reviewable.io -->

2024-01-30 06:37 UTC, kailun-qin reviewed
> Reviewed 6 of 10 files at r1, 1 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/2)* status: all files reviewed, 3 unresolved discussions (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/2#-NpO3zkmB_USpKVqQDbZ:-NpO3zkmB_USpKVqQDb_:b-gz0ood) (no related file):*
Sorry but I don't have approving/requesting changes privilege for this repo. @woju @dimakuv Would you pls kindly check and add me into the list? Thanks!

___
___
*[`README.rst` line 8 at r3](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/2#-NpO377i0Rlnxrw_0uPS:-NpO377i0Rlnxrw_0uPT:bo2ao1g) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/4b6c973736c98abb7b747c859f3ced9037e2f5cf/README.rst#L8)):*
> ```reStructuredText
> ===============================
> 
> Steps common to all distros
> ```

For the common Gramine installation steps, why not directly point to https://gramine.readthedocs.io/en/stable/installation.html#install-gramine-packages? Or anything special?
___
*[`.github/ISSUE_TEMPLATE.md` line 6 at r3](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/2#-NpNy4qL-rqK5QMVCIkb:-NpNy4qM9pdarizD8dnv:br6ou09) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/4b6c973736c98abb7b747c859f3ced9037e2f5cf/.github/ISSUE_TEMPLATE.md#L6)):*
> ```Markdown
> Paste any logs using three backticks (```).
> 
> IMPORTANT: please do not post general questions here;
> ```

Is the sentence complete? If so, we should use a period. If not, we should point users with general questions to elsewhere.



_Code quote:_
```Markdown
here;
```


<!-- Sent from Reviewable.io -->

2024-01-30 06:38 UTC, kailun-qin reviewed
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/2)* status: all files reviewed, 3 unresolved discussions (waiting on @woju)



<!-- Sent from Reviewable.io -->

2024-01-30 07:35 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/2)* status: all files reviewed, 3 unresolved discussions (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/2#-NpO3zkmB_USpKVqQDbZ:-NpOHin1D_DOBtnGUiRD:byu2h3n) (no related file):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Sorry but I don't have approving/requesting changes privilege for this repo. @woju @dimakuv Would you pls kindly check and add me into the list? Thanks!
</blockquote></details>

@kailun-qin Please try now, you were added.

___


<!-- Sent from Reviewable.io -->

2024-01-30 08:24 UTC, kailun-qin requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/2)* status: all files reviewed, 3 unresolved discussions (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/2#-NpO3zkmB_USpKVqQDbZ:-NpOSp-ZCwmepDKwfQzY:b-ucfknh) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@kailun-qin Please try now, you were added.
</blockquote></details>

Thanks!

___


<!-- Sent from Reviewable.io -->

2024-01-31 10:43 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/2)* status: 9 of 10 files reviewed, 3 unresolved discussions (waiting on @dimakuv and @kailun-qin)

___
*[`-- commits` line 16 at r3](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/2#-NpJ76y13Mi7tZCfoohL):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Do you want this second commit to be seen in the final merge, or should we squash it?
</blockquote></details>

As discussed in the meeting, we'll squash all commits from whole PR train. Please do not merge this PR until all initial PRs are reviewed.
___
*[`README.rst` line 8 at r3](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/2#-NpO377i0Rlnxrw_0uPS:-NpU2pDJ5o9LMOUsh38D:b-9t1nth) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/4b6c973736c98abb7b747c859f3ced9037e2f5cf/README.rst#L8)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

For the common Gramine installation steps, why not directly point to https://gramine.readthedocs.io/en/stable/installation.html#install-gramine-packages? Or anything special?
</blockquote></details>

There will be after we merge, that I'll build packages and you'll be able to install from `contrib` component from official repository, like `gramine-ratls-maa`:

```
deb https://packages.gramineproject.io/ bullseye main contrib
#                                                     ^^^^^^^
```

Cf. "Installation instructions" in https://github.com/gramineproject/contrib/releases/tag/v1.6, except the problem is, this repo has some newer packages in dependencies, so unlike RATLS-MAA, there will be distro-specific section about which distros can be used and which can not.

Main docs do not tell people to add `contrib` as of now. So either I won't be able to point to those instructions, or we add `contrib` to official quickstart docs (without discussing which component contains what, because there's no space for that). I can do either of those things.

Another thing that I hope will disappear is section about 23.10, which will be gone after 24.04 LTS (April this year, so in 3 months).

Last but not least, this project is aimed at absolute beginners, people who have background in webapps, not in CoCo, so I'm not sure if I want to point to another instruction in the middle of this one. I would prefer to just tell people to `apt-get install gramine-scaffolding` and put relevant packages in the dependencies.
___
*[`.github/ISSUE_TEMPLATE.md` line 6 at r3](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/2#-NpNy4qL-rqK5QMVCIkb:-NpU4Rpx2pHBEPt_r31g:b4hagp5) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/4b6c973736c98abb7b747c859f3ced9037e2f5cf/.github/ISSUE_TEMPLATE.md#L6)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Is the sentence complete? If so, we should use a period. If not, we should point users with general questions to elsewhere.
</blockquote></details>

Done. Fixed, thanks!


<!-- Sent from Reviewable.io -->

2024-01-31 13:27 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/2)* status: all files reviewed, 3 unresolved discussions (waiting on @dimakuv and @kailun-qin)

___
*[`README.rst` line 8 at r3](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/2#-NpO377i0Rlnxrw_0uPS:-NpUgwZq8WP2l_6cJEEV:b-iw5sa4) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/4b6c973736c98abb7b747c859f3ced9037e2f5cf/README.rst#L8)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

There will be after we merge, that I'll build packages and you'll be able to install from `contrib` component from official repository, like `gramine-ratls-maa`:

```
deb https://packages.gramineproject.io/ bullseye main contrib
#                                                     ^^^^^^^
```

Cf. "Installation instructions" in https://github.com/gramineproject/contrib/releases/tag/v1.6, except the problem is, this repo has some newer packages in dependencies, so unlike RATLS-MAA, there will be distro-specific section about which distros can be used and which can not.

Main docs do not tell people to add `contrib` as of now. So either I won't be able to point to those instructions, or we add `contrib` to official quickstart docs (without discussing which component contains what, because there's no space for that). I can do either of those things.

Another thing that I hope will disappear is section about 23.10, which will be gone after 24.04 LTS (April this year, so in 3 months).

Last but not least, this project is aimed at absolute beginners, people who have background in webapps, not in CoCo, so I'm not sure if I want to point to another instruction in the middle of this one. I would prefer to just tell people to `apt-get install gramine-scaffolding` and put relevant packages in the dependencies.
</blockquote></details>

+1 to what Woju said.


<!-- Sent from Reviewable.io -->

2024-02-01 05:54 UTC, kailun-qin approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/2)* status: all files reviewed, 1 unresolved discussion (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2024-03-13 12:07 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/2)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-03-15 08:45 UTC, dimakuv approved these changes
> Reviewed 120 of 120 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/2)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-03-15 08:46 UTC, closed without merging