The Big Scaffolding Adoption, part 2: The actual scaffolding
gramineproject/gramine-scaffolding pull request #3
Opened 2024-01-24 16:06 UTC by woju

2024-02-14 14:05 UTC, dimakuv requested changes
> Reviewed 69 of 69 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/3)* status: all files reviewed, 77 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

___
*[`pyproject.toml` line 14 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/3#-Nqb0FFWCHysYpF5GgAk:-Nqb0FFWCHysYpF5GgAl:b-164lf3) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/a717f5f9b986b88e390908bab196c5a9bb82acce/pyproject.toml#L14)):*
> ```TOML
> readme = "README.rst"
> dependencies = [
>     "Jinja2",
> ```

Why is this with a capital letter?
___
*[`graminescaffolding/__main__.py` line 17 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/3#-Nqb0e6x4NJNY0NZJFkz:-Nqb0e6x4NJNY0NZJFl-:b-2aeu2b) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/a717f5f9b986b88e390908bab196c5a9bb82acce/graminescaffolding/__main__.py#L17)):*
> ```Python
> import click
> 
> #from .frameworks.common.builder import GramineBuilder
> ```

Debugging leftover?
___
*[`graminescaffolding/__main__.py` line 65 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/3#-Nqb0yoQBwH639X_TjrB:-Nqb0yoQBwH639X_TjrC:bqfh2js) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/a717f5f9b986b88e390908bab196c5a9bb82acce/graminescaffolding/__main__.py#L65)):*
> ```Python
>     """
> 
> @main.command('detect')
> ```

Did you describe this `detect` command in documentation? I don't remember this.
___
*[`graminescaffolding/__main__.py` line 86 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/3#-Nqb1J9wDnl8yWPXjYCl:-Nqb1J9wDnl8yWPXjYCm:b-vvnppq) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/a717f5f9b986b88e390908bab196c5a9bb82acce/graminescaffolding/__main__.py#L86)):*
> ```Python
>         ctx, project_dir, _builder.SCAG_CONFIG_FILE)
>     if not docker_id:
>         return 0
> ```

Shouldn't this be `1` or some other error code?
___
*[`graminescaffolding/__main__.py` line 112 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/3#-Nqb2fb46zFLx1f7qt9I:-Nqb2fb46zFLx1f7qt9J:b-4zmrf0) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/a717f5f9b986b88e390908bab196c5a9bb82acce/graminescaffolding/__main__.py#L112)):*
> ```Python
>         if not os.path.exists(project_dir):
>             if not bootstrap:
>                 raise ValueError('The directory doesn\'t exist. Please create a '
> ```

Should be `The project directory`
___
*[`graminescaffolding/__main__.py` line 136 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/3#-Nqb36WEB8cVFpHvbhLD:-Nqb36WEB8cVFpHvbhLE:b2lk0iu) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/a717f5f9b986b88e390908bab196c5a9bb82acce/graminescaffolding/__main__.py#L136)):*
> ```Python
>     help='The framework used by the scaffolded application.')
> @gramine_option_prompt('--project_dir', required=True, type=str,
>     default=os.getcwd(), prompt='Your\'s app directory is',
> ```

`Your`, no need for the apostrophe
___
*[`graminescaffolding/__main__.py` line 149 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/3#-Nqb3fqp79533X6T0OQu:-Nqb3fqp79533X6T0OQv:b-xieoa0) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/a717f5f9b986b88e390908bab196c5a9bb82acce/graminescaffolding/__main__.py#L149)):*
> ```Python
> 
>     Returns:
>         str: path to project directory, can be used when standalone_mode is
> ```

What's a standalone mode? I don't see it being really used anywhere.
___
*[`graminescaffolding/__main__.py` line 161 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/3#-Nqb47Y7AAkyguzLpubr:-Nqb47Y7AAkyguzLpubs:bke20mf) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/a717f5f9b986b88e390908bab196c5a9bb82acce/graminescaffolding/__main__.py#L161)):*
> ```Python
>     parser = framework.cmdline_setup_parser(project_dir, passthrough_env)
>     if bootstrap:
>         args = framework.bootstrap_defaults
> ```

Does this silently overwrite `args` passed by the user (if the user also specified `--bootstrap`)?
___
*[`graminescaffolding/__main__.py` line 205 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/3#-Nqb4p5d9wMv6629ZpTF:-Nqb4p5d9wMv6629ZpTG:b-3jtnxr) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/a717f5f9b986b88e390908bab196c5a9bb82acce/graminescaffolding/__main__.py#L205)):*
> ```Python
> def build_step(ctx, project_dir, conf):
>     """
>     Real steps for build Gramine application using Scaffolding framework.
> ```

`building`
___
*[`graminescaffolding/__main__.py` line 215 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/3#-Nqb58VQA28cAmbHSx8L:-Nqb58VQA28cAmbHSx8M:bqk9kuq) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/a717f5f9b986b88e390908bab196c5a9bb82acce/graminescaffolding/__main__.py#L215)):*
> ```Python
>         data = tomli.load(file)
> 
>     buildertype = gramine_load_framework(data['application']['framework'])
> ```

Is it normal that if the config file doesn't contain `application.framework`, Python fails with a stack trace?
___
*[`graminescaffolding/__main__.py` line 241 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/3#-Nqb5ecC8virfmNK3Sac:-Nqb5ecC8virfmNK3Sad:bap39g6) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/a717f5f9b986b88e390908bab196c5a9bb82acce/graminescaffolding/__main__.py#L241)):*
> ```Python
>     help='Specify different mrenclave')
> @click.option('--mrsigner',
>     help='Specify different mrenclave')
> ```

`mrsigner`
___
*[`graminescaffolding/__main__.py` line 245 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/3#-Nqb5n2t6crI8eHZkCCm:-Nqb5n2t6crI8eHZkCCn:btq827x) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/a717f5f9b986b88e390908bab196c5a9bb82acce/graminescaffolding/__main__.py#L245)):*
> ```Python
>     help='Allow debug enclave (INSECURE)', default=None)
> @click.option('--allow-outdated-tcb-insecure/--no-allow-outdated-tcb-insecure',
>     help='Allow OUTDATED_TCB (INSECURE)', default=None)
> ```

There are more options (though only these two are relevant to e.g. Microsoft MAA). See https://gramine.readthedocs.io/en/stable/attestation.html#ra-tls-verify-epid-so

Do we want to add them? I don't remember the discussion in the Docs PR...
___
*[`graminescaffolding/__main__.py` line 274 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/3#-Nqb6PoS7uQtheRAYjrh:-Nqb6PoS7uQtheRAYjri:b-8o41w9) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/a717f5f9b986b88e390908bab196c5a9bb82acce/graminescaffolding/__main__.py#L274)):*
> ```Python
>         verify = verify or config['scag-client']['attestation']
>     except LookupError:
>         ctx.fail('missing --verify option')
> ```

What is this confusing error message? Shouldn't it be more like `user wanted to --verify, but no applicable attestation settings found in config file`?
___
*[`graminescaffolding/__main__.py` line 286 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/3#-Nqb6e5O-7Vs_aDtxpwq:-Nqb6e5O-7Vs_aDtxpwr:bqbhwn9) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/a717f5f9b986b88e390908bab196c5a9bb82acce/graminescaffolding/__main__.py#L286)):*
> ```Python
>         verify_cb_kwds['mrenclave'] = mrenclave
>     if mrsigner is not None:
>         verify_cb_kwds['mrsigner'] = mrenclave
> ```

Oops! Should be `= mrsigner`
___
*[`graminescaffolding/__main__.py` line 289 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/3#-Nqb6nwl-xQrYeeWqgij:-Nqb6nwl-xQrYeeWqgik:bfmd6xv) ([raw file](https://github.com [...]

2024-02-21 11:49 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/3)* status: 50 of 69 files reviewed, 77 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv, @mkow, @omeg, @osho, and @oshogbo)

___
*[`pyproject.toml` line 14 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/3#-Nqb0FFWCHysYpF5GgAk:-Nr0MipuCKOkxVzrtZ9l:b-d5mray) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/a717f5f9b986b88e390908bab196c5a9bb82acce/pyproject.toml#L14)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why is this with a capital letter?
</blockquote></details>

It's the canonical name for the python *distribution*: https://pypi.org/project/Jinja2/.

In python's packaging universe, a "distribution" is an archive containing one or more python *modules* and/or *packages*. The name of the distribution may or may not match any of the *packages*/*modules* that it contains. Yes, usually *distribution* contains just one *package* and the name matches, but a certain Armin Ronacher tends to name his Python distributions with capital letter, while the *module*/*package* is still all lowercase: https://pypi.org/org/pallets/ (but he didn't do it for `click` for example). This doesn't really matter, PyPI and Python tooling generally ignore case differences and it's impossible to typosquat a distribution on pypi that differs only in character cases, so it would also be OK to write it all lowercase, `jinja2`. But since you ask, well, now you know. :) This isn't BTW the worst problem with python packaging, unless you ask for more I'll keep explanation of the rest to myself, thank you.
___
*[`graminescaffolding/__main__.py` line 17 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/3#-Nqb0e6x4NJNY0NZJFkz:-Nr1AmOJ44pwfKrX3_Lv:b-9glnp1) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/a717f5f9b986b88e390908bab196c5a9bb82acce/graminescaffolding/__main__.py#L17)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Debugging leftover?
</blockquote></details>

Fixed. Not debugging, it was refactoring — during one round when class for builder lived in different module.
___
*[`graminescaffolding/__main__.py` line 65 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/3#-Nqb0yoQBwH639X_TjrB:-Nr1BKZ-9I0Zj7Z68Psx:bwo3irv) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/a717f5f9b986b88e390908bab196c5a9bb82acce/graminescaffolding/__main__.py#L65)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Did you describe this `detect` command in documentation? I don't remember this.
</blockquote></details>

https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4/Documentation/manpages/scag-detect.rst#..r5
___
*[`graminescaffolding/__main__.py` line 86 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/3#-Nqb1J9wDnl8yWPXjYCl:-Nr1EhCU7WX9d6KL6n8M:b-caamop) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/a717f5f9b986b88e390908bab196c5a9bb82acce/graminescaffolding/__main__.py#L86)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Shouldn't this be `1` or some other error code?
</blockquote></details>

I don't recall. @oshogbo?
___
*[`graminescaffolding/__main__.py` line 112 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/3#-Nqb2fb46zFLx1f7qt9I:-Nr1EyRJ-tCrJKf3jIYB:b-896fix) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/a717f5f9b986b88e390908bab196c5a9bb82acce/graminescaffolding/__main__.py#L112)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Should be `The project directory`
</blockquote></details>

Done.
___
*[`graminescaffolding/__main__.py` line 136 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/3#-Nqb36WEB8cVFpHvbhLD:-Nr1F3ck5frmYrrWAzO6:b-896fix) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/a717f5f9b986b88e390908bab196c5a9bb82acce/graminescaffolding/__main__.py#L136)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`Your`, no need for the apostrophe
</blockquote></details>

Done.
___
*[`graminescaffolding/__main__.py` line 149 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/3#-Nqb3fqp79533X6T0OQu:-Nr1FHSv3XebMmCYLJ1m:b5xwv36) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/a717f5f9b986b88e390908bab196c5a9bb82acce/graminescaffolding/__main__.py#L149)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What's a standalone mode? I don't see it being really used anywhere.
</blockquote></details>

https://click.palletsprojects.com/en/8.1.x/api/#click.BaseCommand.main

It's about 15 lines below, and another one in quickstart.
___
*[`graminescaffolding/__main__.py` line 161 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/3#-Nqb47Y7AAkyguzLpubr:-Nr1FgPj7AWrss1-8P2N:b3toadr) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/a717f5f9b986b88e390908bab196c5a9bb82acce/graminescaffolding/__main__.py#L161)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Does this silently overwrite `args` passed by the user (if the user also specified `--bootstrap`)?
</blockquote></details>

Looks like so. @oshogbo why it's like that?
___
*[`graminescaffolding/__main__.py` line 205 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/3#-Nqb4p5d9wMv6629ZpTF:-Nr1FnyzBYXVd5YORezQ:b-896fix) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/a717f5f9b986b88e390908bab196c5a9bb82acce/graminescaffolding/__main__.py#L205)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`building`
</blockquote></details>

Done.
___
*[`graminescaffolding/__main__.py` line 215 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/3#-Nqb58VQA28cAmbHSx8L:-Nr1FqTp6nA7tvAIh-Ha:b-lptu99) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/a717f5f9b986b88e390908bab196c5a9bb82acce/graminescaffolding/__main__.py#L215)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Is it normal that if the config file doesn't contain `application.framework`, Python fails with a stack trace?
</blockquote></details>

It probably shouldn't.
___
*[`graminescaffolding/__main__.py` line 241 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/3#-Nqb5ecC8virfmNK3Sac:-Nr1GKAHCOe1mtodfcHY:b-896fix) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/a717f5f9b986b88e390908bab196c5a9bb82acce/graminescaffolding/__main__.py#L241)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`mrsigner`
</blockquote></details>

Done.
___
*[`graminescaffolding/__main__.py` line 245 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/3#-Nqb5n2t6crI8eHZkCCm:-Nr1GS2J1ZUBk7yhvG53:bdvlc1z) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/a717f5f9b986b88e390908bab196c5a9bb82acce/graminescaffolding/__main__.py#L245)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

There are more options (though only these two are relevant to e.g. Microsoft MAA). See https://gramine.readthedocs.io/en/stable/attestation.html#ra-tls-verify-epid-so

Do we want to add them? I don't remember the discussion in the Docs PR...
</blockquote></details>

I don't want to add all the options, most of them are config [...]

2024-02-26 13:49 UTC, dimakuv reviewed
> Reviewed 19 of 19 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/3)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @omeg, @osho, and @oshogbo)

___
*[`graminescaffolding/templates/frameworks/dotnet/app.manifest.template` line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/3#-Nqbmw8VCFk5pOiWYU0l:-Nr_d_Mq24Oe5kyjpcEy:b-221n0m) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/a717f5f9b986b88e390908bab196c5a9bb82acce/graminescaffolding/templates/frameworks/dotnet/app.manifest.template#L6)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Yes. Do you want this reflected in framework name, e.g. `dotnet7` instead of `dotnet`?
</blockquote></details>

No, I'm ok with how it is currently.


<!-- Sent from Reviewable.io -->

2024-02-28 10:01 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/3)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv, @omeg, and @osho)

___
*[`graminescaffolding/__main__.py` line 86 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/3#-Nqb1J9wDnl8yWPXjYCl:-Nrj88k3EZt3S92AvQM4:b-1g27rm) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/a717f5f9b986b88e390908bab196c5a9bb82acce/graminescaffolding/__main__.py#L86)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

I don't recall. @oshogbo?
</blockquote></details>

Yes, should be.
Unfortunately, I can't fix this as I don't have written permission for this branch. Heres the patch:

```
From 74157c8854bbf85fb2426056c32a8a94eecb55d0 Mon Sep 17 00:00:00 2001
From: Mariusz Zaborski <oshogbo@invisiblethingslab.com>
Date: Wed, 28 Feb 2024 10:59:29 +0100
Subject: [PATCH] Fix return code.

Signed-off-by: Mariusz Zaborski <oshogbo@invisiblethingslab.com>
---
 graminescaffolding/__main__.py | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git graminescaffolding/__main__.py graminescaffolding/__main__.py
index b4d93ec..c0726a5 100644
--- graminescaffolding/__main__.py
+++ graminescaffolding/__main__.py
@@ -82,7 +82,7 @@ def quickstart(ctx):
     docker_id, docker_run_cmd = build_step(
         ctx, project_dir, _builder.SCAG_CONFIG_FILE)
     if not docker_id:
-        return 0
+        return 1
     print_docker_usage(docker_id, docker_run_cmd)
     if not click.confirm('Do you want to run it now?'):
         return 0
```
___
*[`graminescaffolding/__main__.py` line 161 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/3#-Nqb47Y7AAkyguzLpubr:-Nrj8YkGCBuVDlugetgF:b6yqve2) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/a717f5f9b986b88e390908bab196c5a9bb82acce/graminescaffolding/__main__.py#L161)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Looks like so. @oshogbo why it's like that?
</blockquote></details>

The args contains additional information, for example, what is an entry point for the project.
When we use boostraped version all of this is predefined.


<!-- Sent from Reviewable.io -->

2024-02-28 10:11 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/3)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv, @omeg, and @osho)

___
*[`graminescaffolding/builder.py` line 478 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/3#-NqbhQoF1MKDILOh9pUs:-NrjBVax7Cg8sX2s4cgA:b-riarpo) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/a717f5f9b986b88e390908bab196c5a9bb82acce/graminescaffolding/builder.py#L478)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

I think I told @oshogbo this was wrong idea to put nginx in frameworks. I'll correct this now...
</blockquote></details>

I don't recall that discussion.
But the change is fine with me.
___
*[`graminescaffolding/templates/frameworks/java_gradle/app.manifest.template` line 9 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/3#-NqbsBBo399XVIW6tv2a:-NrjAKw7Ab3pePPYgBsX:b-s7dx7f) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/a717f5f9b986b88e390908bab196c5a9bb82acce/graminescaffolding/templates/frameworks/java_gradle/app.manifest.template#L9)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

@oshogbo ?
</blockquote></details>

It's to limit the initial allocation done by Java. Java allocates a lot of memory that it doesn't use later on. We just try to limit how much space its uses.
https://www.mastertheboss.com/java/how-to-solve-java-lang-outofmemoryerror-compressed-class-space-error/?utm_content=cmp-true
___
*[`graminescaffolding/templates/frameworks/java_jar/app.manifest.template` line 9 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/3#-NqbsdEo5xlugbsfXHRc:-NrjAuHb43qU72DX2O3P:b-7ropln) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/a717f5f9b986b88e390908bab196c5a9bb82acce/graminescaffolding/templates/frameworks/java_jar/app.manifest.template#L9)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

@oshogbo ^
</blockquote></details>

ditto
___
*[`graminescaffolding/templates/frameworks/python_plain/app.manifest.template` line 10 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/3#-Nqbvchq4-oswb5ARCCp:-NrjBBjY6lvtZAygOIYG:b8jzgs8) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/a717f5f9b986b88e390908bab196c5a9bb82acce/graminescaffolding/templates/frameworks/python_plain/app.manifest.template#L10)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

@oshogbo do you remember why this was done?
</blockquote></details>

It was stolen from:
https://github.com/gramineproject/gramine/blob/master/CI-Examples/python/python.manifest.template

Cite:
```
# Python's NumPy spawns as many threads as there are CPU cores, and each thread
# consumes a chunk of memory, so on large machines 1G enclave size may be not enough.
# We limit the number of spawned threads via OMP_NUM_THREADS env variable.
```


<!-- Sent from Reviewable.io -->

2024-02-28 12:57 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/3)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @osho, @oshogbo, and @woju)

___
*[`graminescaffolding/__main__.py` line 161 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/3#-Nqb47Y7AAkyguzLpubr:-NrjlcGE925f0UGmnyv8:b41o0qf) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/a717f5f9b986b88e390908bab196c5a9bb82acce/graminescaffolding/__main__.py#L161)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

The args contains additional information, for example, what is an entry point for the project.
When we use boostraped version all of this is predefined.
</blockquote></details>

Shouldn't we write a warning at least, that user args are discarded in favor of bootstrap args?
___
*[`graminescaffolding/templates/frameworks/dotnet/app.manifest.template` line 17 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/3#-NqbnH6JCYh21e4x2oMo:-Nrjm5Ia8OJVS2V4OHbz:b-yeylcz) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/a717f5f9b986b88e390908bab196c5a9bb82acce/graminescaffolding/templates/frameworks/dotnet/app.manifest.template#L17)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

I'm not sure either. This was written by @omeg, and it works.
</blockquote></details>

Ok, whatever. This seems to be needed, though I don't understand its purpose: https://github.com/dotnet/dotnet-docker/issues/3997
___
*[`graminescaffolding/templates/frameworks/expressjs/app.manifest.template` line 71 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/3#-NqbpHfo0cMpQKVBpuyx:-NrjmEtE6uexK_ESb7OF:bhoruvg) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/a717f5f9b986b88e390908bab196c5a9bb82acce/graminescaffolding/templates/frameworks/expressjs/app.manifest.template#L71)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

@osho why this is like that?
</blockquote></details>

@oshogbo Ping here
___
*[`graminescaffolding/templates/frameworks/koajs/app.manifest.template` line 70 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/3#-NqbuiPh3fgoS1tZo9FR:-NrjmL3835K-L6dY1CT8:bhoruvg) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/a717f5f9b986b88e390908bab196c5a9bb82acce/graminescaffolding/templates/frameworks/koajs/app.manifest.template#L70)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

I'm not so sure, it might be that this is needed. Usually there's symlink `/lib -> /usr/lib`, and some processes might use `/lib` paths. @oshogbo Why this is like that?
</blockquote></details>

@oshogbo Ping here
___
*[`graminescaffolding/templates/frameworks/python_plain/app.manifest.template` line 10 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/3#-Nqbvchq4-oswb5ARCCp:-NrjmVnmDeq_9CgMOlNr:b2m9ma1) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/a717f5f9b986b88e390908bab196c5a9bb82acce/graminescaffolding/templates/frameworks/python_plain/app.manifest.template#L10)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

It was stolen from:
https://github.com/gramineproject/gramine/blob/master/CI-Examples/python/python.manifest.template

Cite:
```
# Python's NumPy spawns as many threads as there are CPU cores, and each thread
# consumes a chunk of memory, so on large machines 1G enclave size may be not enough.
# We limit the number of spawned threads via OMP_NUM_THREADS env variable.
```
</blockquote></details>

But your example/template has nothing to do with NumPy?


<!-- Sent from Reviewable.io -->

2024-03-11 11:35 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/3)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @osho)

___
*[`graminescaffolding/__main__.py` line 161 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/3#-Nqb47Y7AAkyguzLpubr:-NsT1Aet94v29Z9wZmdb:bb9o395) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/a717f5f9b986b88e390908bab196c5a9bb82acce/graminescaffolding/__main__.py#L161)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Shouldn't we write a warning at least, that user args are discarded in favor of bootstrap args?
</blockquote></details>

Proposed patch: https://github.com/intel/ScaffoldingForGramine/pull/51
___
*[`graminescaffolding/templates/frameworks/expressjs/app.manifest.template` line 71 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/3#-NqbpHfo0cMpQKVBpuyx:-NshHtbe61XYL8zvF-f2:b-qsitjn) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/a717f5f9b986b88e390908bab196c5a9bb82acce/graminescaffolding/templates/frameworks/expressjs/app.manifest.template#L71)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@oshogbo Ping here
</blockquote></details>

It seems that we can drop it:
https://github.com/intel/ScaffoldingForGramine/pull/52
___
*[`graminescaffolding/templates/frameworks/koajs/app.manifest.template` line 70 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/3#-NqbuiPh3fgoS1tZo9FR:-NshHxXN8r96t8dD_3ar:bu25z92) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/a717f5f9b986b88e390908bab196c5a9bb82acce/graminescaffolding/templates/frameworks/koajs/app.manifest.template#L70)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@oshogbo Ping here
</blockquote></details>

Ditto:
https://github.com/intel/ScaffoldingForGramine/pull/52
___
*[`graminescaffolding/templates/frameworks/python_plain/app.manifest.template` line 10 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/3#-Nqbvchq4-oswb5ARCCp:-NsT0ei41ptTzD0_2hmu:btqcv76) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/a717f5f9b986b88e390908bab196c5a9bb82acce/graminescaffolding/templates/frameworks/python_plain/app.manifest.template#L10)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

But your example/template has nothing to do with NumPy?
</blockquote></details>

My idea was that numpy is quite popular, and we can leave it as the template is generic for Python.
And it might not be obvious why Python stops working.

But I agree we can drop it.


<!-- Sent from Reviewable.io -->

2024-03-11 12:08 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/3)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @osho, @oshogbo, and @woju)

___
*[`graminescaffolding/__main__.py` line 86 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/3#-Nqb1J9wDnl8yWPXjYCl:-NshOvICAscgqjmENkjF:b-kicaa1) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/a717f5f9b986b88e390908bab196c5a9bb82acce/graminescaffolding/__main__.py#L86)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Yes, should be.
Unfortunately, I can't fix this as I don't have written permission for this branch. Heres the patch:

```
From 74157c8854bbf85fb2426056c32a8a94eecb55d0 Mon Sep 17 00:00:00 2001
From: Mariusz Zaborski <oshogbo@invisiblethingslab.com>
Date: Wed, 28 Feb 2024 10:59:29 +0100
Subject: [PATCH] Fix return code.

Signed-off-by: Mariusz Zaborski <oshogbo@invisiblethingslab.com>
---
 graminescaffolding/__main__.py | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git graminescaffolding/__main__.py graminescaffolding/__main__.py
index b4d93ec..c0726a5 100644
--- graminescaffolding/__main__.py
+++ graminescaffolding/__main__.py
@@ -82,7 +82,7 @@ def quickstart(ctx):
     docker_id, docker_run_cmd = build_step(
         ctx, project_dir, _builder.SCAG_CONFIG_FILE)
     if not docker_id:
-        return 0
+        return 1
     print_docker_usage(docker_id, docker_run_cmd)
     if not click.confirm('Do you want to run it now?'):
         return 0
```
</blockquote></details>

@woju Will you fix here?
___
*[`graminescaffolding/__main__.py` line 161 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/3#-Nqb47Y7AAkyguzLpubr:-NshP2eKDBZr5rOd-JYK:b-k6vcxy) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/a717f5f9b986b88e390908bab196c5a9bb82acce/graminescaffolding/__main__.py#L161)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Proposed patch: https://github.com/intel/ScaffoldingForGramine/pull/51
</blockquote></details>

@woju Will you apply the patch to this PR?
___
*[`graminescaffolding/templates/frameworks/expressjs/app.manifest.template` line 71 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/3#-NqbpHfo0cMpQKVBpuyx:-NshPC627K-goruxhWBE:b-ko9jyc) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/a717f5f9b986b88e390908bab196c5a9bb82acce/graminescaffolding/templates/frameworks/expressjs/app.manifest.template#L71)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

It seems that we can drop it:
https://github.com/intel/ScaffoldingForGramine/pull/52
</blockquote></details>

@osho That PR timed out on your CI, please check.
___
*[`graminescaffolding/templates/frameworks/python_plain/app.manifest.template` line 10 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/3#-Nqbvchq4-oswb5ARCCp:-NshPKpw6ejRgBw4vjuA:b9b09xe) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/a717f5f9b986b88e390908bab196c5a9bb82acce/graminescaffolding/templates/frameworks/python_plain/app.manifest.template#L10)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

My idea was that numpy is quite popular, and we can leave it as the template is generic for Python.
And it might not be obvious why Python stops working.

But I agree we can drop it.
</blockquote></details>

Well, alternatively you can write a comment explaining the need for this envvar. Otherwise it's just a mysterious manifest option.


<!-- Sent from Reviewable.io -->

2024-03-11 12:10 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/3)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv, @osho, and @woju)

___
*[`graminescaffolding/templates/frameworks/expressjs/app.manifest.template` line 71 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/3#-NqbpHfo0cMpQKVBpuyx:-NshPrAr1djhk02yu5zx:bjo102x) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/a717f5f9b986b88e390908bab196c5a9bb82acce/graminescaffolding/templates/frameworks/expressjs/app.manifest.template#L71)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@osho That PR timed out on your CI, please check.
</blockquote></details>

Please notice the second run.


<!-- Sent from Reviewable.io -->

2024-03-11 12:29 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/3)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @osho, @oshogbo, and @woju)

___
*[`graminescaffolding/templates/frameworks/expressjs/app.manifest.template` line 71 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/3#-NqbpHfo0cMpQKVBpuyx:-NshULgE7CUr6tZakwF4:b-4sh072) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/a717f5f9b986b88e390908bab196c5a9bb82acce/graminescaffolding/templates/frameworks/expressjs/app.manifest.template#L71)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Please notice the second run.
</blockquote></details>

True, resolving that question.

@woju Will you apply the patch to this PR?


<!-- Sent from Reviewable.io -->

2024-03-13 11:37 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/3)* status: 63 of 69 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @osho)

___
*[`graminescaffolding/__main__.py` line 86 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/3#-Nqb1J9wDnl8yWPXjYCl:-NsrW5_a9OnNHmOwqbMi:b-896fix) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/a717f5f9b986b88e390908bab196c5a9bb82acce/graminescaffolding/__main__.py#L86)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@woju Will you fix here?
</blockquote></details>

Done.
___
*[`graminescaffolding/__main__.py` line 161 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/3#-Nqb47Y7AAkyguzLpubr:-NsrXzaEEar5HoSD0ZmY:b-896fix) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/a717f5f9b986b88e390908bab196c5a9bb82acce/graminescaffolding/__main__.py#L161)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@woju Will you apply the patch to this PR?
</blockquote></details>

Done.
___
*[`graminescaffolding/templates/frameworks/expressjs/app.manifest.template` line 71 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/3#-NqbpHfo0cMpQKVBpuyx:-NsrZa135uMBWLMvRajG:bq1j3v1) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/a717f5f9b986b88e390908bab196c5a9bb82acce/graminescaffolding/templates/frameworks/expressjs/app.manifest.template#L71)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

True, resolving that question.

@woju Will you apply the patch to this PR?
</blockquote></details>

Done.

Took liberty to drop that `X` commit. In the future, you can just `git commit --amend` in place, that changes date and causes new hash, so zuul in webhook mode will re-run. (Zuul in app mode has a button in Github).
___
*[`graminescaffolding/templates/frameworks/koajs/app.manifest.template` line 70 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/3#-NqbuiPh3fgoS1tZo9FR:-NsrYgiGDuqWzXdSmWJi:b-896fix) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/a717f5f9b986b88e390908bab196c5a9bb82acce/graminescaffolding/templates/frameworks/koajs/app.manifest.template#L70)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Ditto:
https://github.com/intel/ScaffoldingForGramine/pull/52
</blockquote></details>

Done.
___
*[`graminescaffolding/templates/frameworks/python_plain/app.manifest.template` line 10 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/3#-Nqbvchq4-oswb5ARCCp:-NsrZXK4DEJYVOtXIcJY:b-q53y60) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/a717f5f9b986b88e390908bab196c5a9bb82acce/graminescaffolding/templates/frameworks/python_plain/app.manifest.template#L10)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Well, alternatively you can write a comment explaining the need for this envvar. Otherwise it's just a mysterious manifest option.
</blockquote></details>

Done. Added comment.


<!-- Sent from Reviewable.io -->

2024-03-13 12:06 UTC, dimakuv approved these changes
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/3)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-03-13 12:44 UTC, merged