The Big Scaffolding Adoption, part 3: Documentation
gramineproject/gramine-scaffolding pull request #4
Opened 2024-01-24 16:06 UTC by woju

2024-01-29 08:34 UTC, dimakuv requested changes
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4)* status: all files reviewed, 66 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4#-NpJ8uaKCBTC3TWbV3p5:-NpJ8uaKCBTC3TWbV3p6:bugyw5y) (no related file):*
Could we have a RTD web site for this? I'd like to see how it renders currently (and I'm lazy to build on my machine locally). We'll need this anyway, so you could enable this branch for now.

Also, the old documentation doesn't have pages like `templates`: https://gramine-scaffolding.readthedocs.io/en/latest/ (unless I miss something)

___
___
*[`Documentation/conf.py` line 23 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4#-NpJ7mzz5uZekUfzfJl6:-NpJ7mzz5uZekUfzfJl7:b-jeeqhj) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/66f657496bf896bc6b102b19b9c1080ab4e53fea/Documentation/conf.py#L23)):*
> ```Python
> 
> man_pages = [
>     ('manpages/scag-build', 'scag-build', 'Build Gramine Scaffolding application', _man_pages_author, 1),
> ```

Why do you have the same explanation for `scag-build`, `scag-quickstart` and `scag-setup`?
___
*[`Documentation/configuration.rst` line 21 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4#-NpJ9UerEQ6N4Nt0SJ3Y:-NpJ9UerEQ6N4Nt0SJ3Z:bg9p2fj) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/66f657496bf896bc6b102b19b9c1080ab4e53fea/Documentation/configuration.rst#L21)):*
> ```reStructuredText
>     - ``python_plain``
>     - ``flask``
>     - ``nodejs_plain``
> ```

There are clearly more frameworks currently available: https://github.com/gramineproject/gramine-scaffolding/pull/3/files
___
*[`Documentation/configuration.rst` line 28 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4#-NpJ9tc04Sfe5zqyOAg4:-NpJ9tc04Sfe5zqyOAg5:b-103sht) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/66f657496bf896bc6b102b19b9c1080ab4e53fea/Documentation/configuration.rst#L28)):*
> ```reStructuredText
>     directory.
> 
> ``sgx.sign_args`` (array)
> ```

Should be more specifically `array of strings`?
___
*[`Documentation/configuration.rst` line 29 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4#-NpJ9iSYDnDhzbsVG2bL:-NpJ9iSYDnDhzbsVG2bM:b7u4dnc) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/66f657496bf896bc6b102b19b9c1080ab4e53fea/Documentation/configuration.rst#L29)):*
> ```reStructuredText
> 
> ``sgx.sign_args`` (array)
>     Extra arguments to :command:`gramine-sgx-sign` command. Can be used to
> ```

What does it mean `extra arguments`? What are the arguments that SCAG automatically uses then?
___
*[`Documentation/configuration.rst` line 40 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4#-NpJ9zvXC_9H2k4tMTNS:-NpJ9zvXC_9H2k4tMTNT:b-tqvozx) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/66f657496bf896bc6b102b19b9c1080ab4e53fea/Documentation/configuration.rst#L40)):*
> ```reStructuredText
>     INSECURE. Build debug enclave. Debug enclaves do not give any security
>     guarantees and should fail attestation, but can be used for debugging
>     running application.
> ```

`For debugging running application` -- I can't parse this. Do you mean `For debugging an application`? And if you meant `running`, then what does it mean; can you debug a non-running application?
___
*[`Documentation/configuration.rst` line 48 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4#-NpJAEWX5fGoqhZkbPps:-NpJAEWX5fGoqhZkbPpt:bv0r4ie) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/66f657496bf896bc6b102b19b9c1080ab4e53fea/Documentation/configuration.rst#L48)):*
> ```reStructuredText
> 
>     - ``dcap`` (the default)
>     - ``epid``
> ```

But if a user specifies `epid`, then there are two more mandatory manifest options (see https://gramine.readthedocs.io/en/stable/manifest-syntax.html#attestation-and-quotes). Did you test it? How does it work? And if not tested, maybe just remove `epid` then?
___
*[`Documentation/configuration.rst` line 64 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4#-NpJAXlo4s8_KVxjuPQM:-NpJAXlo4s8_KVxjuPQN:b-durv0q) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/66f657496bf896bc6b102b19b9c1080ab4e53fea/Documentation/configuration.rst#L64)):*
> ```reStructuredText
> 
> ``nodejs_plain.application`` (string)
>     Path to the main script inside application's directory.
> ```

Is this mandatory? Can't you have a sane default like `main.py`?
___
*[`Documentation/configuration.rst` line 70 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4#-NpJA_VE7OoTmX-n-aK1:-NpJA_VE7OoTmX-n-aK2:b-durv0q) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/66f657496bf896bc6b102b19b9c1080ab4e53fea/Documentation/configuration.rst#L70)):*
> ```reStructuredText
> 
> ``python_plain.application`` (string)
>     Path to the main script inside application's directory.
> ```

Is this mandatory? Can't you have a sane default like `main.py`?
___
*[`Documentation/configuration.rst` line 70 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4#-NpJAa2MDlaGc556pY94:-NpJAa2MDlaGc556pY95:b35ag2u) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/66f657496bf896bc6b102b19b9c1080ab4e53fea/Documentation/configuration.rst#L70)):*
> ```reStructuredText
> 
> ``python_plain.application`` (string)
>     Path to the main script inside application's directory.
> ```

Please add options to other supported frameworks (e.g. .NET, Java)
___
*[`Documentation/deployment.rst` line 15 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4#-NpJBLto-Ue3jMFNA4JP:-NpJBLto-Ue3jMFNA4JQ:b-huq6zm) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/66f657496bf896bc6b102b19b9c1080ab4e53fea/Documentation/deployment.rst#L15)):*
> ```reStructuredText
> :file:`/app/app.sig` inside the container).
> 
> Instead of delivering the container to Ops, developer should deliver
> ```

`the container` -> `the SCAG-built container`?
___
*[`Documentation/hacking.rst` line 9 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4#-NpJBcB970LCJqau0eog:-NpJBcB970LCJqau0eoh:b54wzy2) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/66f657496bf896bc6b102b19b9c1080ab4e53fea/Documentation/hacking.rst#L9)):*
> ```reStructuredText
> ------------
> 
> There's a class called ``Builder`` (see :file:`gramineproject/builder.py`) which
> ```

`gramineproject/...`? Looks like a copy-paste fail. Here and everywhere in this PR.
___
*[`Documentation/hacking.rst` line 13 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4#-NpJC6dfE9GoixPoqAFO:-NpJC6dfE9GoixPoqAFP:b-gwql98) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/66f657496bf896bc6b102b19b9c1080ab4e53fea/Documentation/hacking.rst#L13)):*
> ```reStructuredText
> steps:
> 
> 1. Templates are rendered into magic directory.
> ```

`magic`? I'd prefer `temporary` or just `.scag/`
___
*[`Documentation/hacking.rst` line 14 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4#-NpJDpnpEcykuMY5lR0O:-NpJDpnpEcykuMY5lR0P:byagpwj) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/66f657496bf896bc6b102b19b9c1080ab4e53fea/Documentation/hacking.rst#L14)):*
> ```reStructuredText
> 
> 1. Templates are rendered into magic directory.
> 2. System image is installed into chroot directory.
> ```

Where is this chroot directory actually? I.e. what is its dir name on the host?
___
*[`Documentation/hacking.rst` line 33 at r1](https://re [...]

2024-01-31 15:49 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4)* status: 3 of 13 files reviewed, 66 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4#-NpJ8uaKCBTC3TWbV3p5:-NpU6ZSf1PkuqY8FILgS:b-7xnwib) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could we have a RTD web site for this? I'd like to see how it renders currently (and I'm lazy to build on my machine locally). We'll need this anyway, so you could enable this branch for now.

Also, the old documentation doesn't have pages like `templates`: https://gramine-scaffolding.readthedocs.io/en/latest/ (unless I miss something)
</blockquote></details>

For now you can look at https://zuul.gramineproject.io/logs/22/22/a9c30fb25afc1715b3beff33017e6660cc160359/check/build-docs/ade69bd/html/, which contains previous version (before fixes from this review). https://gramine-scaffolding.rtfd.io is still pointing at previous repo.

___
___
*[`Documentation/conf.py` line 23 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4#-NpJ7mzz5uZekUfzfJl6:-NpU6wUrAB__wJwpQ8Yj:b-wutjh7) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/66f657496bf896bc6b102b19b9c1080ab4e53fea/Documentation/conf.py#L23)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you have the same explanation for `scag-build`, `scag-quickstart` and `scag-setup`?
</blockquote></details>

That's a result of abusing Copy-Paste (et al.) Algorithm. Fixed.
___
*[`Documentation/configuration.rst` line 21 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4#-NpJ9UerEQ6N4Nt0SJ3Y:-NpUFhQo0GicvXYT6AVO:b-896fix) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/66f657496bf896bc6b102b19b9c1080ab4e53fea/Documentation/configuration.rst#L21)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

There are clearly more frameworks currently available: https://github.com/gramineproject/gramine-scaffolding/pull/3/files
</blockquote></details>

Done.
___
*[`Documentation/configuration.rst` line 28 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4#-NpJ9tc04Sfe5zqyOAg4:-NpUFPqh6zEk5WdINOgw:b-qwc4te) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/66f657496bf896bc6b102b19b9c1080ab4e53fea/Documentation/configuration.rst#L28)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Should be more specifically `array of strings`?
</blockquote></details>

I can do that.
___
*[`Documentation/configuration.rst` line 29 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4#-NpJ9iSYDnDhzbsVG2bL:-NpU8U7y5dR10FXSJQrQ:bq3wqg5) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/66f657496bf896bc6b102b19b9c1080ab4e53fea/Documentation/configuration.rst#L29)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What does it mean `extra arguments`? What are the arguments that SCAG automatically uses then?
</blockquote></details>

Normal arguments are `--manifest`, `--output` and `--sigfile`. Everything else (like `--key` in example below, or `--with` which is not in examples) you can put here. Should I add something about this?
___
*[`Documentation/configuration.rst` line 40 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4#-NpJ9zvXC_9H2k4tMTNS:-NpU8xy78x0c8wYvcncM:b-4shl8z) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/66f657496bf896bc6b102b19b9c1080ab4e53fea/Documentation/configuration.rst#L40)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`For debugging running application` -- I can't parse this. Do you mean `For debugging an application`? And if you meant `running`, then what does it mean; can you debug a non-running application?
</blockquote></details>

That's a linguistic question, because "debugging" in strict sense means messing with process' memory, but in general sense it's a development process of removing bugs. So IDK, if you accept that just removing bugs by reasoning about how program behaves without resorting to a tool called "debugger", then I think this is OK.

Would you care to suggest a wording that would avoid this linguistic problem altogether, while being understandable for people who never touched GDB (like "fullstack" developers)?
___
*[`Documentation/configuration.rst` line 48 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4#-NpJAEWX5fGoqhZkbPps:-NpUBg1d9I7MXREjErcC:b-r0clng) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/66f657496bf896bc6b102b19b9c1080ab4e53fea/Documentation/configuration.rst#L48)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

But if a user specifies `epid`, then there are two more mandatory manifest options (see https://gramine.readthedocs.io/en/stable/manifest-syntax.html#attestation-and-quotes). Did you test it? How does it work? And if not tested, maybe just remove `epid` then?
</blockquote></details>

Yes, it needs those options, you can add them by overriding manifest template (see `templates.rst`). No, I didn't test. I'm not sure if I want to just remove this option (or even just the mention of it in the docs). Can I just point to `templates.rst` here?
___
*[`Documentation/configuration.rst` line 64 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4#-NpJAXlo4s8_KVxjuPQM:-NpUDJWM98Q0pNzPZNyX:b5mkyfi) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/66f657496bf896bc6b102b19b9c1080ab4e53fea/Documentation/configuration.rst#L64)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Is this mandatory? Can't you have a sane default like `main.py`?
</blockquote></details>

Yes, it's mandatory in `scag.toml` (explicit is better than implicit), but the user typically does not need to fill it in. The value comes from `scag-quickstart` tool, which does have a default, pointing to the example file (`app.js` in case of `nodejs_plain`).
___
*[`Documentation/configuration.rst` line 70 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4#-NpJA_VE7OoTmX-n-aK1:-NpUDkmp21GMDHXITax4:bldem2t) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/66f657496bf896bc6b102b19b9c1080ab4e53fea/Documentation/configuration.rst#L70)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Is this mandatory? Can't you have a sane default like `main.py`?
</blockquote></details>

See above (but `hello_world.py`).
___
*[`Documentation/configuration.rst` line 70 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4#-NpJAa2MDlaGc556pY94:-NpUFoeCDm-dgBQsDvxZ:b-896fix) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/66f657496bf896bc6b102b19b9c1080ab4e53fea/Documentation/configuration.rst#L70)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add options to other supported frameworks (e.g. .NET, Java)
</blockquote></details>

Done.
___
*[`Documentation/deployment.rst` line 15 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4#-NpJBLto-Ue3jMFNA4JP:-NpUFsat8jayQgkTugR_:b-g5wcl) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/66f657496bf896bc6b102b19b9c1080ab4e53fea/Documentation/deployment.rst#L15)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`the container` -> `the SCAG-bui [...]

2024-02-02 13:41 UTC, dimakuv requested changes
> Reviewed 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

___
*[`Documentation/configuration.rst` line 29 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4#-NpJ9iSYDnDhzbsVG2bL:-NpdwUNj5_ih7g9OZPDl:b-xflj7i) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/66f657496bf896bc6b102b19b9c1080ab4e53fea/Documentation/configuration.rst#L29)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Normal arguments are `--manifest`, `--output` and `--sigfile`. Everything else (like `--key` in example below, or `--with` which is not in examples) you can put here. Should I add something about this?
</blockquote></details>

Ah, I get it now. No need to change anything.
___
*[`Documentation/configuration.rst` line 40 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4#-NpJ9zvXC_9H2k4tMTNS:-NpdwkKj9a56wYjLUAh9:b-3wz2it) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/66f657496bf896bc6b102b19b9c1080ab4e53fea/Documentation/configuration.rst#L40)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

That's a linguistic question, because "debugging" in strict sense means messing with process' memory, but in general sense it's a development process of removing bugs. So IDK, if you accept that just removing bugs by reasoning about how program behaves without resorting to a tool called "debugger", then I think this is OK.

Would you care to suggest a wording that would avoid this linguistic problem altogether, while being understandable for people who never touched GDB (like "fullstack" developers)?
</blockquote></details>

Why not just `for debugging an application`?
___
*[`Documentation/configuration.rst` line 48 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4#-NpJAEWX5fGoqhZkbPps:-Npdx4va8IaRIr4Aam92:b-e3wzus) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/66f657496bf896bc6b102b19b9c1080ab4e53fea/Documentation/configuration.rst#L48)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Yes, it needs those options, you can add them by overriding manifest template (see `templates.rst`). No, I didn't test. I'm not sure if I want to just remove this option (or even just the mention of it in the docs). Can I just point to `templates.rst` here?
</blockquote></details>

Well, you added the additional explanations here. I'm resolving.
___
*[`Documentation/hacking.rst` line 14 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4#-NpJDpnpEcykuMY5lR0O:-NpdxllL6rhY0CEDtQzl:bmt24wj) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/66f657496bf896bc6b102b19b9c1080ab4e53fea/Documentation/hacking.rst#L14)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

This section should be rewritten after intel/ScaffoldingForGramine#48. There are two extra steps, and more things happen in docker.
</blockquote></details>

Let's keep the comment blocking then.
___
*[`Documentation/templates.rst` line 95 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4#-NpJHopCAx--vfb4KidN:-Npe-bci0C95qi7pqXpy:b-s04ehr) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/66f657496bf896bc6b102b19b9c1080ab4e53fea/Documentation/templates.rst#L95)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

No, I meant `<project_dir>/templates/Dockerfile`. Reworded.

Why do you mention `<new-framework>`? This is not for *developers* creating new frameworks (that was `hacking.rst`), this is for *users* configuring existing frameworks. If you got confused, should I make that distinction more clear somewhere in this document?
</blockquote></details>

Yeah, I think I confused the new-framework docs and the configure-existing-framework docs. I understand now.
___
*[`Documentation/manpages/scag-build.rst` line 12 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4#-NpJI3MVDrrRNt8cYhbd:-Npe-ncLDVONIzyx90fq:bxb6q6h) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/66f657496bf896bc6b102b19b9c1080ab4e53fea/Documentation/manpages/scag-build.rst#L12)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

The first one is without `-`, it's `build` subcommand of `scag` multiplexer command. The other one is standalone CLI command, with the same options available.

BTW you can also `python3 -m graminescaffolding build`, I didn't mention it here.
</blockquote></details>

Ah, I didn't notice the `-`
___
*[`Documentation/manpages/scag-build.rst` line 32 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4#-NpJIAF1Dd1TGF2PC7cG:-Npe-s8O8N9axccu7NXw:b-rb9wk9) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/66f657496bf896bc6b102b19b9c1080ab4e53fea/Documentation/manpages/scag-build.rst#L32)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Yes, `scag.toml`.
</blockquote></details>

Shouldn't you specify a default value in this manpage?
___
*[`Documentation/manpages/scag-client.rst` line 190 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4#-NpJJejX95L5b-OP4EjF:-Npe117x6FqUwvQJirqh:b-i1yys4) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/66f657496bf896bc6b102b19b9c1080ab4e53fea/Documentation/manpages/scag-client.rst#L190)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

What this thing should really contain? Is it path to file or the actual key in PEM format? I haven't found thorough documentation of this envvar (`RA_TLS_IAS_PUB_KEY_PEM`).
</blockquote></details>

It's the actual key in PEM format, like this: https://github.com/gramineproject/gramine/blob/1cf1f46646646a3b9c6b371e67c80e945577456a/tools/sgx/common/ias.c#L28
___
*[`Documentation/manpages/scag-client.rst` line 190 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4#-NpJJa83-OZh3G46SNrR:-Npe19-VA498lIT3L7sf:b-l5285a) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/66f657496bf896bc6b102b19b9c1080ab4e53fea/Documentation/manpages/scag-client.rst#L190)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

IDK, why?
</blockquote></details>

Actually, you're right. The key belongs to the URL parts, so makes sense to have here.
___
*[`Documentation/manpages/scag-client.rst` line 218 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4#-NpJJjdt41LAm68bIN0i:-Npe1GYwC4lLkf0bEQ4O:bocu6g1) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/66f657496bf896bc6b102b19b9c1080ab4e53fea/Documentation/manpages/scag-client.rst#L218)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Why?
</blockquote></details>

Here it seems to make sense (in contrast to the EPID case): the version is part of the final construct URL for REST commands.
___
*[`Documentation/manpages/scag-client.rst` line 224 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4#-NpJJuUD4FhhOewjFp25:-Npe1OSK2yXLa57Z8SUw:bhmn5xg) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/66f657496bf896bc6b102b19b9c1080ab4e53fea/Documentation/manpages/scag-client.rst#L224)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

It's for completeness with how manpages should be written (https://manpages.debian.org/bookworm/manpages/man-pages.7.en.html#Sections_within [...]

2024-02-06 21:18 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4)* status: 5 of 13 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[`Documentation/configuration.rst` line 29 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4#-NpJ9iSYDnDhzbsVG2bL:-NpygyvN9bZRYl8sgBNj:bsqu4v8) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/66f657496bf896bc6b102b19b9c1080ab4e53fea/Documentation/configuration.rst#L29)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ah, I get it now. No need to change anything.
</blockquote></details>

Nevertheless I've enumerated those for completeness. It's a technicality, but it might avoid nasty surprise, should someone attempt to change them. Changing them does not work, because "normal" arguments are supplied after user's, so if user writes them, they're silently ignored. So it might be a frustration to find out experimentally.
___
*[`Documentation/configuration.rst` line 40 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4#-NpJ9zvXC_9H2k4tMTNS:-NpyhS1kCnVCtD5Apipb:bvsbhin) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/66f657496bf896bc6b102b19b9c1080ab4e53fea/Documentation/configuration.rst#L40)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why not just `for debugging an application`?
</blockquote></details>

Because "debugging" might not be understood by people of javascript pedigree. I've elaborated somewhat, maybe this version is better?
___
*[`Documentation/deployment.rst` line 15 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4#-NpJBLto-Ue3jMFNA4JP:-NpyjWBP0gZUhhNpn-1H:b-896fix) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/66f657496bf896bc6b102b19b9c1080ab4e53fea/Documentation/deployment.rst#L15)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

This whole document will be false after moving building to docker (see https://github.com/intel/ScaffoldingForGramine/pull/48). I'll rewrite it after I merge that upstream and transplant into #3. Let's keep this thread blocked for now.
</blockquote></details>

Done.
___
*[`Documentation/hacking.rst` line 14 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4#-NpJDpnpEcykuMY5lR0O:-NpymQOO21TrwJHNOIMF:b-2lvylb) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/66f657496bf896bc6b102b19b9c1080ab4e53fea/Documentation/hacking.rst#L14)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Let's keep the comment blocking then.
</blockquote></details>

I've rewritten this section.
___
*[`Documentation/hacking.rst` line 39 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4#-NpJCeHHBB8m_8I6SjgG:-NpymhE97fX8t-RSY074:beb3x9s) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/66f657496bf896bc6b102b19b9c1080ab4e53fea/Documentation/hacking.rst#L39)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Will rewrite, this will be in `Dockerfile`.
</blockquote></details>

N/A, gramine-manifest was moved.
___
*[`Documentation/hacking.rst` line 40 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4#-NpJDBJfCXDm0JxcMYFk:-Npymkgp1Z5QBSz8XSfY:bophpqj) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/66f657496bf896bc6b102b19b9c1080ab4e53fea/Documentation/hacking.rst#L40)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

After intel/ScaffoldingForGramine#48.
</blockquote></details>

N/A, was redone. `customize.sh` is not that important anymore to describe here, I don't want to mention it more than I already did.
___
*[`Documentation/manpages/scag-build.rst` line 32 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4#-NpJIAF1Dd1TGF2PC7cG:-Npynfhx8jlwut3fFpEV:b-896fix) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/66f657496bf896bc6b102b19b9c1080ab4e53fea/Documentation/manpages/scag-build.rst#L32)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Shouldn't you specify a default value in this manpage?
</blockquote></details>

Done.
___
*[`Documentation/manpages/scag-client.rst` line 190 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4#-NpJJejX95L5b-OP4EjF:-NpyoNXpCfJj9vg7iYch:b-896fix) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/66f657496bf896bc6b102b19b9c1080ab4e53fea/Documentation/manpages/scag-client.rst#L190)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

It's the actual key in PEM format, like this: https://github.com/gramineproject/gramine/blob/1cf1f46646646a3b9c6b371e67c80e945577456a/tools/sgx/common/ias.c#L28
</blockquote></details>

Done.
___
*[`Documentation/manpages/scag-client.rst` line 218 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4#-NpJJjdt41LAm68bIN0i:-NpyoWoSAnp_FzCTDQKQ:b-896fix) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/66f657496bf896bc6b102b19b9c1080ab4e53fea/Documentation/manpages/scag-client.rst#L218)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Here it seems to make sense (in contrast to the EPID case): the version is part of the final construct URL for REST commands.
</blockquote></details>

Done.
___
*[`Documentation/manpages/scag-client.rst` line 224 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4#-NpJJuUD4FhhOewjFp25:-NpyoZx02yG5DuUe2rvx:b-896fix) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/66f657496bf896bc6b102b19b9c1080ab4e53fea/Documentation/manpages/scag-client.rst#L224)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't mind either way. Then please add it to other man pages, but I'm not blocking.
</blockquote></details>

Done.
___
*[`Documentation/manpages/scag-detect.rst` line 18 at r2](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4#-Npe1gY90nZ-cShIQym1:-Npyw1on1Q9YRViDjkW-:b-896fix) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/83c91a44a4c9a33ae6f8afa0774cf56a87887a1c/Documentation/manpages/scag-detect.rst#L18)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Unfinished sentence?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-07 08:58 UTC, dimakuv requested changes
> Reviewed 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

___
*[`Documentation/configuration.rst` line 40 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4#-NpJ9zvXC_9H2k4tMTNS:-Nq1jXZI0UAngz-54hJ0:b-z3id0u) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/66f657496bf896bc6b102b19b9c1080ab4e53fea/Documentation/configuration.rst#L40)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Because "debugging" might not be understood by people of javascript pedigree. I've elaborated somewhat, maybe this version is better?
</blockquote></details>

Thanks, better
___
*[`Documentation/hacking.rst` line 14 at r3](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4#-Nq1kxHX60M9QmYZQKED:-Nq1kxHX60M9QmYZQKEE:b1g5d2v) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/1df0d17f9bdaea069eb470cd896132ed8cbcea5c/Documentation/hacking.rst#L14)):*
> ```reStructuredText
> 
> 1. Templates are rendered into ``.scag/`` directory.
> 2. Base system image is installed into temporary chroot directory and is
> ```

What is a `base system`? Is that Gramine related files? Could you somehow briefly explain this?
___
*[`Documentation/hacking.rst` line 16 at r3](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4#-Nq1kjdH38tPHEIFTG2_:-Nq1kjdIA_Owtjr8lqZS:bobt1yr) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/1df0d17f9bdaea069eb470cd896132ed8cbcea5c/Documentation/hacking.rst#L16)):*
> ```reStructuredText
> 2. Base system image is installed into temporary chroot directory and is
>    archived into temporary tarball ``.scag/rootfs.tar``.
> 3. A base system docker is created from ``rootfs.tar`` (see
> ```

`base system docker` is meaningless. Did you mean `base system docker image`?

Also, shouldn't you write `Docker` with a capital D?
___
*[`Documentation/hacking.rst` line 20 at r3](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4#-Nq1l9Pp5swNnSIJlHwc:-Nq1l9Pp5swNnSIJlHwd:b7mitpi) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/1df0d17f9bdaea069eb470cd896132ed8cbcea5c/Documentation/hacking.rst#L20)):*
> ```reStructuredText
> 4. Main docker image is built (from ``Dockerfile`` template, rendered to
>    ``.scag/Dockerfile``). This is the step that varies the most according to
>    specific framework. ``gramine-manifest`` is run at the end of this stage.
> ```

This `main docker image` is derived from the `base system docker image`, right? Would be good to mention this, for completeness.
___
*[`Documentation/hacking.rst` line 21 at r3](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4#-Nq1lJKJB3mM_SMr3pAt:-Nq1lJKJB3mM_SMr3pAu:b-wzkndq) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/1df0d17f9bdaea069eb470cd896132ed8cbcea5c/Documentation/hacking.rst#L21)):*
> ```reStructuredText
>    ``.scag/Dockerfile``). This is the step that varies the most according to
>    specific framework. ``gramine-manifest`` is run at the end of this stage.
> 5. Contents of this customised docker image is extracted into temporary
> ```

`is` -> `are`
___
*[`Documentation/hacking.rst` line 23 at r3](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4#-Nq1lShO7BJDge1NYTvq:-Nq1lShO7BJDge1NYTvr:b-i7hjxk) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/1df0d17f9bdaea069eb470cd896132ed8cbcea5c/Documentation/hacking.rst#L23)):*
> ```reStructuredText
> 5. Contents of this customised docker image is extracted into temporary
>    directory and ``gramine-sgx-sign`` is ran *outside of the docker build
>    process*.
> ```

This seems to be done for security reasons? Can you mention the rationale?

Also, it means that Gramine (moreover, a compatible Gramine version) must be installed on the host?
___
*[`Documentation/hacking.rst` line 25 at r3](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4#-Nq1lclH7PKc5IHjq39n:-Nq1lclH7PKc5IHjq39o:b-roj4uf) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/1df0d17f9bdaea069eb470cd896132ed8cbcea5c/Documentation/hacking.rst#L25)):*
> ```reStructuredText
>    process*.
> 4. Artifacts from ``gramine-sgx-sign`` (``app.manifest.sgx`` and ``app.sig``)
>    are used to build third Docker container, based on the second (cusomised)
> ```

`customized` (typo)
___
*[`Documentation/hacking.rst` line 37 at r3](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4#-Nq1lr149qzJKj4GR3K2:-Nq1lr149qzJKj4GR3K3:b-ovtfvz) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/1df0d17f9bdaea069eb470cd896132ed8cbcea5c/Documentation/hacking.rst#L37)):*
> ```reStructuredText
> render additional templates as required.
> 
> Step 2 is executed as single command, ``mmdebstrap``. ``mmdebstrap`` is a tool
> ```

This first sentence doesn't make much sense now. Maybe:
```
Step 2 is executed via ``mmdebstrap``.
```
___
*[`Documentation/hacking.rst` line 133 at r3](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4#-Nq1mDZo6d0bW9460Bk4:-Nq1mDZo6d0bW9460Bk5:b-djg7d1) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/1df0d17f9bdaea069eb470cd896132ed8cbcea5c/Documentation/hacking.rst#L133)):*
> ```reStructuredText
>     ``{% extends 'Dockerfile' %}``). ``{{ apt.install('pkg1', 'pkg2', ...)``
>     will emit ``RUN apt-get ...`` invocation that will correctly install the
>     set of packages given as arguments.
> ```

What's the use for this macro? Why can't the user directly write `RUN apt-get ...`?
___
*[`Documentation/manpages/scag-client.rst` line 210 at r3](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4#-Nq1mOKG3y9ZvNjmAUPI:-Nq1mOKG3y9ZvNjmAUPJ:b-44juqz) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/1df0d17f9bdaea069eb470cd896132ed8cbcea5c/Documentation/manpages/scag-client.rst#L210)):*
> ```reStructuredText
> ``epid.ias-pub-key-pem`` (string)
>     Public key for IAS in PEM format (multi-line string starting with
>     ``-----BEGIN PUBLIC KEY-----``)
> ```

Need a dot at the end of the sentence


<!-- Sent from Reviewable.io -->

2024-02-07 16:34 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4)* status: 9 of 13 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[`Documentation/hacking.rst` line 14 at r3](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4#-Nq1kxHX60M9QmYZQKED:-Nq1prz08hKUpuD6Jl2n:b-896fix) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/1df0d17f9bdaea069eb470cd896132ed8cbcea5c/Documentation/hacking.rst#L14)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What is a `base system`? Is that Gramine related files? Could you somehow briefly explain this?
</blockquote></details>

Done.
___
*[`Documentation/hacking.rst` line 16 at r3](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4#-Nq1kjdH38tPHEIFTG2_:-Nq3Ngwg2z1mlDNSTu8p:b-896fix) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/1df0d17f9bdaea069eb470cd896132ed8cbcea5c/Documentation/hacking.rst#L16)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`base system docker` is meaningless. Did you mean `base system docker image`?

Also, shouldn't you write `Docker` with a capital D?
</blockquote></details>

Done.
___
*[`Documentation/hacking.rst` line 20 at r3](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4#-Nq1l9Pp5swNnSIJlHwc:-Nq3P1K9AqPArz2yse14:b-896fix) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/1df0d17f9bdaea069eb470cd896132ed8cbcea5c/Documentation/hacking.rst#L20)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This `main docker image` is derived from the `base system docker image`, right? Would be good to mention this, for completeness.
</blockquote></details>

Done.
___
*[`Documentation/hacking.rst` line 21 at r3](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4#-Nq1lJKJB3mM_SMr3pAt:-Nq3P0_FEqqGLqprxM71:b-896fix) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/1df0d17f9bdaea069eb470cd896132ed8cbcea5c/Documentation/hacking.rst#L21)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`is` -> `are`
</blockquote></details>

Done.
___
*[`Documentation/hacking.rst` line 23 at r3](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4#-Nq1lShO7BJDge1NYTvq:-Nq1wWTpA9lB8IG3u-TU:bwgxpbg) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/1df0d17f9bdaea069eb470cd896132ed8cbcea5c/Documentation/hacking.rst#L23)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This seems to be done for security reasons? Can you mention the rationale?

Also, it means that Gramine (moreover, a compatible Gramine version) must be installed on the host?
</blockquote></details>

No, this is done for compatibility. If you have configured plugins for HSM, you don't need to configure them in docker.

Yes, it requires the same version. It's being taken care of in two stages: first, when installing `gramine-scaffolding` package, `gramine (>= 1.6)` is pulled by dependencies. Then, when building a container, `get_gramine_dependency()` in `builder.py` detects the exact version and `create_chroot()` passes this version to mmdebstrap's `--include` so either the correct version is installed, or the whole mmdebstrap fails.

This arrangement mainly suffers from cache invalidation problem: if you update Gramine on workstation, you need to rebuild all apps you intend to resign from the ground up, because all Docker layers refer to incorrect base image. We currently rebuild rootfs every time, but might cache it in the future.
___
*[`Documentation/hacking.rst` line 25 at r3](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4#-Nq1lclH7PKc5IHjq39n:-Nq3PS9Z9GQHHpOJAdCE:b-896fix) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/1df0d17f9bdaea069eb470cd896132ed8cbcea5c/Documentation/hacking.rst#L25)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`customized` (typo)
</blockquote></details>

Done.
___
*[`Documentation/hacking.rst` line 37 at r3](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4#-Nq1lr149qzJKj4GR3K2:-Nq2D-wZAtYdCqOVLesP:b-896fix) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/1df0d17f9bdaea069eb470cd896132ed8cbcea5c/Documentation/hacking.rst#L37)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This first sentence doesn't make much sense now. Maybe:
```
Step 2 is executed via ``mmdebstrap``.
```
</blockquote></details>

Done.
___
*[`Documentation/hacking.rst` line 133 at r3](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4#-Nq1mDZo6d0bW9460Bk4:-Nq2D4IX6Bxwk-aaTCsY:b8v0tiv) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/1df0d17f9bdaea069eb470cd896132ed8cbcea5c/Documentation/hacking.rst#L133)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What's the use for this macro? Why can't the user directly write `RUN apt-get ...`?
</blockquote></details>

There's some stuff to account for when doing `apt-get install` in Docker: you need to first `apt-get update`, and after install you need to purge cache (to keep image small and also to keep hadolint happy). Obviously you can write that stanza manually, but it gets repetitive quite fast, and in case of `dotnet` you need two such stanzas in one Dockerfile (you need `ca-certificates` installed before doing `apt-get update` that precedes installation of dotnet SDK), which would be plain ugly.

I've moved this section to `templates.rst`.
___
*[`Documentation/manpages/scag-client.rst` line 210 at r3](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4#-Nq1mOKG3y9ZvNjmAUPI:-Nq2d_Xj2BV-TgzvFZRI:b-896fix) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/1df0d17f9bdaea069eb470cd896132ed8cbcea5c/Documentation/manpages/scag-client.rst#L210)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Need a dot at the end of the sentence
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-08 08:41 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4)* status: 9 of 13 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[`Documentation/manpages/scag-client.rst` line 218 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4#-NpJJjdt41LAm68bIN0i:-Nq6s5nR6Q2gkDJhx2mq:b-1x2znw) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/66f657496bf896bc6b102b19b9c1080ab4e53fea/Documentation/manpages/scag-client.rst#L218)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

FYI I've moved both of them to the end. `maa-provider-url` is not mandatory anymore and unlikely to be changed.


<!-- Sent from Reviewable.io -->

2024-02-08 12:54 UTC, dimakuv requested changes
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

___
*[`Documentation/hacking.rst` line 23 at r3](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4#-Nq1lShO7BJDge1NYTvq:-Nq7lwgO9lYjgIcS8B6c:bd96loz) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/1df0d17f9bdaea069eb470cd896132ed8cbcea5c/Documentation/hacking.rst#L23)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

No, this is done for compatibility. If you have configured plugins for HSM, you don't need to configure them in docker.

Yes, it requires the same version. It's being taken care of in two stages: first, when installing `gramine-scaffolding` package, `gramine (>= 1.6)` is pulled by dependencies. Then, when building a container, `get_gramine_dependency()` in `builder.py` detects the exact version and `create_chroot()` passes this version to mmdebstrap's `--include` so either the correct version is installed, or the whole mmdebstrap fails.

This arrangement mainly suffers from cache invalidation problem: if you update Gramine on workstation, you need to rebuild all apps you intend to resign from the ground up, because all Docker layers refer to incorrect base image. We currently rebuild rootfs every time, but might cache it in the future.
</blockquote></details>

Thanks for the great explanation!
___
*[`Documentation/hacking.rst` line 52 at r4](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4#-Nq7m6HW2WdoHn81ITWh:-Nq7m6HW2WdoHn81ITWi:b-fmwkly) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/c0c2a84b4f1fb0b6d0e4a72acd2d629e7e8b5017/Documentation/hacking.rst#L52)):*
> ```reStructuredText
>    :file:`app.sig`) are used to build third Docker container, based on the
>    second (customised) one. The manifest and SIGSTRUCT are added to this
>    container. This is the final container that can be shipped.
> ```

You mention here `container` (3x), but it should be `image`.


<!-- Sent from Reviewable.io -->

2024-02-09 11:35 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4)* status: 12 of 13 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[`Documentation/hacking.rst` line 52 at r4](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4#-Nq7m6HW2WdoHn81ITWh:-Nq8NYmJ-wg6Pqsqa1rN:b-896fix) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/c0c2a84b4f1fb0b6d0e4a72acd2d629e7e8b5017/Documentation/hacking.rst#L52)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You mention here `container` (3x), but it should be `image`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-12 08:05 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/4)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-03-13 12:43 UTC, merged